#define a basic db that holds user info, and the results of the OCR process, and the history of the interactions with the system.

from typing import Optional, List
from datetime import datetime, timezone
from sqlmodel import SQLModel, Field, Relationship
from sqlalchemy import Column, TEXT

# Base model with timestamp fields for created_at and updated_at
# so I don't have to repeat these fields in every model, 
# and also to provide a consistent way to track when records are created and updated.
def utc_now():
    return datetime.now(timezone.utc)
class TimestampMixin(SQLModel):
    created_at: datetime = Field(
        default_factory=utc_now,
        nullable=False
    )
    updated_at: datetime = Field(
        default_factory=utc_now,
        sa_column_kwargs={
            "onupdate": utc_now,
        },
        nullable=False
    )


# User model to store user information, such as username, email, and password hash.and a unique id as foregin key for the OCR results and interaction history.
class User(TimestampMixin, table=True):
    __tablename__ = "users"

    # Using SQLModel's Field with primary_key=True to define the id field as the primary key for the User model,
    # and also allowing it to be optional with default=None, so that it can be automatically generated by the database when a new user is created.
    id: Optional[int] = Field(default=None, primary_key=True)

    email: str = Field(unique=True, index=True)
    username: str = Field(unique=True, index=True)

    #using someone else's password hashing library to hash the password before storing it in the database,
    password_hash: str

    # use this field to control user account status, such as active, suspended, or deleted, 
    # and to implement features like account deactivation or soft deletion without actually removing the user record from the database.
    is_active: bool = Field(default=True)


class FitnessRecord(TimestampMixin, table=True):
    __tablename__ = "fitness_records"

    id: Optional[int] = Field(default=None, primary_key=True)
    
    #health-related information
    age: int = Field(ge=1, le=120)  
    gender: str                     
    height_cm: float                
    weight_kg: float                
    
   
    activity_level: str            
    fitness_goal: str               
    
    # FK to the User model, establishing a relationship between fitness records and users, allowing us to associate each fitness record with a specific user in the database.
    user_id: int = Field(foreign_key="users.id")
    user: User = Relationship(back_populates="fitness_records")

class FitnessReport(TimestampMixin, table=True):
    __tablename__ = "fitness_reports"

    id: Optional[int] = Field(default=None, primary_key=True)
    
    report_content: str = Field(sa_column=Column(TEXT))
    
    analysis_start_date: Optional[datetime] = Field(default=None)
    analysis_end_date: Optional[datetime] = Field(default=None)

    data_summary: Optional[str] = Field(default=None, sa_column=Column(TEXT))
  
    model_used: Optional[str] = Field(default=None)
 
    user_id: int = Field(foreign_key="users.id")
    user: Optional["User"] = Relationship(back_populates="fitness_reports")